#! /bin/bash
echo " Welcome to Secret_Agent_Application"
echo "######################################"
read -p "Enter your name:" name
read -p "Enter your favourite actor:" actor
read -p "Enter your lucky number": lucky
read -p "Enter your favourite dish": dish
first_char_name=$(echo -n $name | cut -c 1)
len=$(echo -n $actor | wc -c)
last_char_actor=$(echo -n $actor | cut -c $len)
no_of_characters_dish=$(echo -n $dish | wc -c)
if [ $first_char_name="d" -a $last_char_actor="r" -a $lucky -eq 7 -a $no_of_characters_dish -ge 6 ];then
echo "Hello Secret Agent ....our next operation is to kill ten sleeping students of the classroom because there are burden to country"
else
echo "Hello $name Thanks for your information"
fi
